CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
		DT_CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		DT_ATUALIZADO_EM DATETIME NOT NULL,
    NM_USUARIO VARCHAR(255) NOT NULL,
    DS_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    DS_SENHA_HASH VARCHAR(255) NOT NULL,
    TP_USUARIO INT NOT NULL, -- 0: Comum, 1: Admin
    
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
		DT_CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		DT_ATUALIZADO_EM DATETIME NOT NULL,
    NM_PRODUTO VARCHAR(255) NOT NULL,
    DS_PRODUTO TEXT,
    NM_CATEGORIA VARCHAR(100),
    FL_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID_PRODUTO)
);

CREATE TABLE VARIACOES_PRODUTO (
    ID_VARIACAO_PRODUTO INT NOT NULL AUTO_INCREMENT,
		DT_CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		DT_ATUALIZADO_EM DATETIME NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DS_TAMANHO VARCHAR(50),
    DS_COR VARCHAR(50),
    VL_PRECO DECIMAL(10, 2) NOT NULL,
    FL_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    URL_IMG VARCHAR(500) NULL,

    CONSTRAINT PK_VARIACOES_PRODUTO PRIMARY KEY(ID_VARIACAO_PRODUTO),
    CONSTRAINT FK_VARIACOES_PRODUTOS FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO) ON DELETE CASCADE -- On delete cascade por sem composição
);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE INT NOT NULL AUTO_INCREMENT,
		DT_CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		DT_ATUALIZADO_EM DATETIME NOT NULL,
    ID_VARIACAO_PRODUTO INT NOT NULL UNIQUE, -- unique pq é 1:1 a cardinalidade
    NR_QUANTIDADE INT NOT NULL DEFAULT 0,	

    CONSTRAINT PK_ESTOQUE PRIMARY KEY(ID_ESTOQUE),
    CONSTRAINT FK_ESTOQUE_VARIACOES FOREIGN KEY (ID_VARIACAO_PRODUTO) REFERENCES VARIACOES_PRODUTO(ID_VARIACAO_PRODUTO) ON DELETE CASCADE -- On delete cascade por sem composição
);

CREATE TABLE VENDAS (
    ID_VENDA INT NOT NULL AUTO_INCREMENT,
		DT_CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		DT_ATUALIZADO_EM DATETIME NOT NULL,
    ID_USUARIO INT,
    DT_VENDA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VL_TOTAL_VENDA DECIMAL(10, 2) NOT NULL,
    TP_STATUS INT NOT NULL,

    CONSTRAINT PK_VENDAS PRIMARY KEY(ID_VENDA),
    CONSTRAINT FK_VENDAS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE SET NULL -- Se deletar o usuário mantém a venda la para o histórico
);

CREATE TABLE ITENS_VENDA (
    ID_ITEM_VENDA INT NOT NULL AUTO_INCREMENT,
		DT_CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		DT_ATUALIZADO_EM DATETIME NOT NULL,
    ID_VENDA INT NOT NULL,
    ID_VARIACAO_PRODUTO INT NOT NULL,
    NR_QUANTIDADE INT NOT NULL,
    VL_PRECO_UNITARIO DECIMAL(10, 2) NOT NULL, -- "Congela" o preço no momento da venda

    CONSTRAINT PK_ITENS_VENDA PRIMARY KEY(ID_ITEM_VENDA),
    CONSTRAINT FK_ITENSVENDA_VENDAS FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA) ON DELETE CASCADE, -- On delete cascade por sem composição
    CONSTRAINT FK_ITENSVENDA_VARIACOES FOREIGN KEY (ID_VARIACAO_PRODUTO) REFERENCES VARIACOES_PRODUTO(ID_VARIACAO_PRODUTO) ON DELETE restrict -- restrict não permite deletar uma variação se tiver alguma venda com ela registrada
);